### PR TITLE
[KFSQA-1183] Explicitly set standard error and standard out buffering…

### PR DESCRIPTION
**Pull request by nkimble**
… to line buffering. Modified code to have all failure data go to standard error instead of standard out.

### CODE REVIEW

**Comment by nkimble** [comment]
Changes only exist on kuality-kfs-cu branch.

**Comment by nkimble** [comment]
Additional changes made per our discussion due to failure output not showing up in server json file.  These changes have been verified with forced failed AFT in a One-Off report build.

**Comment by kyleoliveira** [comment]
Looks good!

**Comment by nkimble** [comment]
Reverting changes due to server runs terminating on first failure and not continuing to next scenario.

**Pull request merged**
